Update README.md
cncf/hugo-netlify-starter pull request #49
Opened 2020-10-28 12:29 UTC by GauravSarkar

Added the version of hugo.
corrected in response to issue #8
Signed-off-by: GauravSarkar <60042820+GauravSarkar@users.noreply.github.com>

2020-10-28 18:32 UTC, nate-double-u commented
Hi @GauravSarkar, thanks for looking into this!

I saw your [comment in the original issue](https://github.com/cncf/hugo-netlify-starter/issues/8#issuecomment-717913328), but would like to respond to it here as the DCO issues are a part of this PR process.

I'm not sure if there is a sign-off method (like a checkbox) in the GitHub UI (like there are in some other git GUIs). Because the sign-off is just a line of text in the commit, it is possible to sign a commit correctly without using the command line. 
However, I do recommend getting familiar with the command line as it makes some of these issues easier to deal with.

Looking at the details of the [DCO check](https://github.com/cncf/hugo-netlify-starter/pull/49/checks?check_run_id=1320598115), it looks like there is a slight discrepancy between what has been provided, and what github is looking for in a sign-off (I wonder if there is a discrepancy between your name in GitHub, and your local .gitconfig name?).

> Commit sha: 5428c91, Author: Gaurav Sarkar, Committer: GitHub; Expected "Gaurav Sarkar 60042820+GauravSarkar@users.noreply.github.com", but got "GauravSarkar 60042820+GauravSarkar@users.noreply.github.com".

2020-10-28 18:33 UTC, nate-double-u requested changes
Please update link to gohugo.io

2020-10-28 18:33 UTC, nate-double-u commented on README.md
> +* **[Hugo](This requires Hugo 9.73+ extended version)(https://gohugo.io/)** as a static site generator
For markdown links, the whole text to be linked needs to be within the `[]` brakets

```suggestion
* **[Hugo (This requires Hugo 9.73+ extended version)](https://gohugo.io/)** as a static site generator
```

2020-10-29 05:31 UTC, GauravSarkar commented
Thanks I have finally sorted out the DCO error and to avoid confusions I have opened a fresh PR #53  with the required changes.

2020-10-29 16:45 UTC, nate-double-u commented
Great, I'll take a look at that PR and close this one.

2020-10-29 16:45 UTC, closed without merging